### PR TITLE
Fix the image PR

### PR DESCRIPTION
**Pull request by plewyllie**

### CODE REVIEW

**Comment by rcarrata** [comment]
LGTM. Great PR!

**Review by rcarrata — COMMENTED** [review]
Yaml folder seems to be a bit confusing, how about change the folder to something more "specific" such as fix-image or something related?

**Comment by plewyllie** [comment]
Makes sense! I changed the folder name

**Review by rcarrata — APPROVED** [review]
LGTM! thx for the PR and the fixes.

**Pull request merged**
